== Exception Handling

Every applications needs to handle cases where normal program execution cannot continue due to some reason.
This may be related to invalid business rules, a service or database is down etc.
The standard way to handle these special cases is by using the the exception mechanism already provided by the Java language.

[NOTE]
====
The Java language allows *unchecked* or *checked* exceptions.
The exception handling in cookbook assumes all exceptions are *unchecked* because of the easy of writing code.
Using *checked* exceptions will force you to always write a try - catch block which leads to unnecessary clutter.
====

=== Business and Technical Exceptions

This cookbook uses custom made exceptions.
They are free to use in your projects.
You can find the source on the Github project.


=== Throw an exception

In its basic form, the exception contains a message. You can throw an exception using the following code:

[source,java,indent=0]
----
public void businessExceptionWithEnum(){
    throw new BusinessException("Something has gone wrong");
}
----

TIP: Each exception contains a specific id used to uniquely find the error details in e.g. a logging file or the database

The following examples illustrate the different options you have in throwing exceptions:

.Throw BusinessException with an error code
[source,java,indent=0]
----
public void businessExceptionWithEnum(){
    throw new BusinessException(ErrorCode.FUNC_ERROR, "Something has gone wrong"); // <1>
}
----
<1> You can use any type of enum you want to represent the error. This case uses the ErrorCode enum

.Throw BusinessException with parameters
[source,java,indent=0]
----
public void businessExceptionWithVariables(){
    throw new BusinessException("Something has gone wrong with data {}","my-data");
}
----

.Throw BusinessException with multiple messages
[source,java,indent=0]
----
public void exceptionWithMultipleMessages(){
    BusinessException exception = new BusinessException("Something has gone wrong");
    exception.add(ErrorCode.FUNC_ERROR,"functional error");
    exception.add(ErrorCode.FUNC_ERROR,"another error");
    throw exception;
}
----

.Throw TechnicalException with a message
[source,java,indent=0]
----
public void technicalExceptionWithMessage(){
    throw new TechnicalException("technical error");
}
----

.Throw TechnicalException from another throwable
[source,java,indent=0]
----
public void technicalExceptionWithThrowable(){
    RuntimeException exception = new RuntimeException("RuntimeException");
    throw new TechnicalException(exception);
}
----

NOTE: Technical exceptions only accept one message compared to BusinessException that keep track of multiple messages

[TIP]
====
*Never loose* the *original exception*.
If you throw a new exception based on an old one, make sure you pass the old one in the constructor as a parameter to keep track of the full stacktrace.
 You'll thank me later.
====



